export const ADD_QUESTION = "ADD_NEW_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";

export const UPDATE_FORM_INFO = "UPDATE_FORM_INFO";
export const UPDATE_STATE_STATUS = "UPDATE_STATE_STATUS";

export const FETCH_FORM_DATA_BY_ID = "FETCH_FORM_DATA_BY_ID";
export const FETCH_RECENT_FORMS = "FETCH_RECENT_FORMS";

export const SAVE_FORM_BY_ID = "SAVE_FORM_BY_ID";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
