
//

export const ADD_NEW_QUESTION = "ADD_NEW_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const UPDATE_INFO_SURVEY = "UPDATE_INFO_SURVEY";
export const UPDATE_QUESTION_TYPE = "UPDATE_QUESTION_TYPE";
export const UPDATE_TEMP_SURVEY_ID = "UPDATE_TEMP_SURVEY_ID";
export const GET_DATA_FROM_DB_BY_ID = "GET_DATA_FROM_DB_BY_ID";
export const UPDATE_SELECTED_QUESTION_TYPE = "UPDATE_SELECTED_QUESTION_TYPE";
export const UPDATE_CURRENT_INDEX = "UPDATE_CURRENT_INDEX";
export const UPDATE_SECTION_BREAK = "UPDATE_SECTION_BREAK";
export const GET_RECENT_FORMS_FROM_DB = "GET_RECENT_FORMS_FROM_DB";
export const UPDATE_SUBMIT_STATUS = "UPDATE_SUBMIT_STATUS";
export const SAVE_FORM_TO_DB = "SAVE_FORM_TO_DB";
export const SAVE_SURVEY_TO_DB = "SAVE_SURVEY_TO_DB";
export const CLEAR_SURVEY = "CLEAR_SURVEY";
export const CLEAR_SUBMIT_STATUS = "CLEAR_SUBMIT_STATUS";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const GET_CLIENT_SURVEY_FROM_DB = "GET_CLIENT_SURVEY_FROM_DB";